version: '3.7'
services:

  petclinic:
    image: spring-petclinic
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_URL=jdbc:mysql://localhost/petclinic
      - DB_USER=petclinic
      - DB_PASSORD=petclinic
    depends_on:
      - petclinicdb

  petclinicdb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
