kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: aksdemos.azurecr.io/spring-petclinic:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: petclinic-db-conn
              key: db_url
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: petclinic-db-conn
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: petclinic-db-conn
              key: db_password
